version: '3'
services:
  mysql:
    image: mysql:8
    # command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test
  ruby:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_DB=test
      - MYSQL_USER=root
      - MYSQL_PWD=password
      - MYSQL_PORT=3306